// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_account_cache_file`, `get_accounts_dir`, `get_app_data_dir`, `get_endfield_dir`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<String> findLoginCachePath() =>
    RustLib.instance.api.crateApiEndfieldFindLoginCachePath();

/// 获取当前所有已保存的账号列表
Future<List<AccountInfo>> getAccountList() =>
    RustLib.instance.api.crateApiEndfieldGetAccountList();

/// 保存当前登录的账号
Future<void> saveCurrentAccount({required String alias}) =>
    RustLib.instance.api.crateApiEndfieldSaveCurrentAccount(alias: alias);

/// 切换到指定账号
Future<void> switchToAccount({required String alias}) =>
    RustLib.instance.api.crateApiEndfieldSwitchToAccount(alias: alias);

/// 删除指定账号
Future<void> deleteAccount({required String alias}) =>
    RustLib.instance.api.crateApiEndfieldDeleteAccount(alias: alias);

class AccountInfo {
  final String alias;
  final PlatformInt64 updatedAt;

  const AccountInfo({required this.alias, required this.updatedAt});

  @override
  int get hashCode => alias.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountInfo &&
          runtimeType == other.runtimeType &&
          alias == other.alias &&
          updatedAt == other.updatedAt;
}
