// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_base_url`, `get_accounts_dir`, `get_config_file_path`, `validate_remote_entry_name`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<void> saveWebdavConfig({required WebDavConfig config}) =>
    RustLib.instance.api.crateApiWebdavSaveWebdavConfig(config: config);

Future<WebDavConfig> loadWebdavConfig() =>
    RustLib.instance.api.crateApiWebdavLoadWebdavConfig();

Future<void> syncToWebdav() =>
    RustLib.instance.api.crateApiWebdavSyncToWebdav();

Future<void> syncToWebdavWithManifest() =>
    RustLib.instance.api.crateApiWebdavSyncToWebdavWithManifest();

Future<void> syncFromWebdav() =>
    RustLib.instance.api.crateApiWebdavSyncFromWebdav();

class WebDavConfig {
  final String url;
  final String username;
  final String? password;
  final String? path;

  const WebDavConfig({
    required this.url,
    required this.username,
    this.password,
    this.path,
  });

  @override
  int get hashCode =>
      url.hashCode ^ username.hashCode ^ password.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavConfig &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          username == other.username &&
          password == other.password &&
          path == other.path;
}
